service: serverless-deployment-demo

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: ap-southeast-2

package:
  individually: true

functions:
  hello:
    handler: Serverless.DeploymentDemo::Serverless.DeploymentDemo.Handler::Hello
    package:
      artifact: bin/release/netcoreapp2.1/artifact.zip
    events:
      - http:
          method: get
          path: hello