service: serverless-deployment-demo

plugins:
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: ap-southeast-2
  tracing: 
    apiGateway: true
    lambda: true
  profile: rezare-personal
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

package:
  individually: true

functions:
  hello:
    handler: Serverless.DeploymentDemo::Serverless.DeploymentDemo.Handler::Hello
    package:
      artifact: bin/release/netcoreapp2.1/artifact.zip
    events:
      - http:
          method: get
          path: hello