service: serverless-deployment-demo

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: ap-southeast-2
  tracing: 
    apiGateway: true
    lambda: true
  profile: rezare-personal
  iamRoleStatements:
    - Effect: "Allow" # xray permissions
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

package:
  individually: true

functions:
  canary:
    handler: Serverless.DeploymentDemo::Serverless.DeploymentDemo.LambdaFunctions::GetTweet_Canary
    package:
      artifact: bin/release/netcoreapp2.1/artifact.zip
    tracing: Active
    events:
      - http:
          method: get
          path: tweet/canary
  linear:
    handler: Serverless.DeploymentDemo::Serverless.DeploymentDemo.LambdaFunctions::GetTweet_Linear
    package:
      artifact: bin/release/netcoreapp2.1/artifact.zip
    tracing: Active
    events:
      - http:
          method: get
          path: tweet/linear