service: serverless-deployment-demo

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: ap-southeast-2
  apiName: api
  tracing: 
    apiGateway: true
    lambda: true
  profile: rezare-personal
  tags:
    owner: chris
    region: ap
    stack: serverless-deployment-demo
  iamRoleStatements:
    - Effect: "Allow" # xray permissions
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
    - Effect: Allow # Canary Deployment Permissions
      Action:
        - codedeploy:*
      Resource:
        - "*"

plugins:
  - serverless-plugin-canary-deployments

package:
  individually: true

functions:
  canary:
    name: lambda-canary
    handler: Serverless.DeploymentDemo::Serverless.DeploymentDemo.LambdaFunctions::GetTweet_Canary
    package:
      artifact: bin/release/netcoreapp2.1/artifact.zip
    tracing: Active
    deploymentSettings:
      type: Canary10Percent5Minutes
      alias: live
    events:
      - http:
          method: get
          path: tweet/canary

  linear:
    name: lambda-linear
    handler: Serverless.DeploymentDemo::Serverless.DeploymentDemo.LambdaFunctions::GetTweet_Linear
    package:
      artifact: bin/release/netcoreapp2.1/artifact.zip
    tracing: Active
    deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: live
    events:
      - http:
          method: get
          path: tweet/linear